import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Normalidad = localFont({
  src: [
    {
      path: '../lib/fonts/NormalidadCompact-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../lib/fonts/NormalidadCompact-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../lib/fonts/NormalidadCompact-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../lib/fonts/NormalidadCompact-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../lib/fonts/NormalidadCompact-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../lib/fonts/NormalidadCompact-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-normalidad-compact',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${Normalidad.className} h-full antialiased`}
    >
      <body className={`${Normalidad.className} min-h-[3000px] flex flex-col overflow-x-hidden`}>{children}</body>
    </html>
  );
}
